security:
  oauth2:
    client:
      client-id: 748708748455-c5hgi0ucrn0j5m2jrpt2tbdl2b9p52lc.apps.googleusercontent.com 
      client-secret: Qg4dh_NocCsUOtol9O2lmbIV
      # 認証画面URI
      user-authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
      # トークン取得用URI
      access-token-uri: https://www.googleapis.com/oauth2/v4/token
      # 認証タイプ
      authorized-grant-types:
        authorization_code
      # formで固定
      authentication-scheme: form
      # スコープ
      scope:
        - https://www.googleapis.com/auth/userinfo.profile
    resource:
      token-info-uri: https://www.googleapis.com/userinfo/v2/me
    sso:
      # リダイレクト先
      login-path: /home
  basic:
    enabled: false